/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#351000",
        "primary-container": "#ff6b01",
        "surface-tint": "#a04100",
        "on-primary": "#ffffff",
        "on-surface-variant": "#5a4136",
        "surface-container-highest": "#f8ddd2",
        "surface-bright": "#fff8f6",
        "surface-container-high": "#fee3d8",
        "on-tertiary-fixed-variant": "#614000",
        "tertiary-container": "#cd8c00",
        "on-secondary": "#ffffff",
        "secondary-container": "#9fc2fe",
        "tertiary-fixed": "#ffddb0",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001b3c",
        "on-tertiary-container": "#452c00",
        "outline-variant": "#e2bfb0",
        "secondary-fixed": "#d5e3ff",
        "on-secondary-container": "#294f83",
        "outline": "#8e7164",
        "inverse-surface": "#3d2d26",
        "tertiary": "#805600",
        "on-surface": "#261812",
        "on-primary-container": "#572000",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#a7c8ff",
        "secondary": "#3a5f94",
        "inverse-primary": "#ffb693",
        "surface-container": "#ffeae1",
        "on-secondary-fixed-variant": "#1f477b",
        "surface-container-low": "#fff1eb",
        "surface": "#fff8f6",
        "primary": "#a04100",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#7a2f00",
        "primary-fixed-dim": "#ffb693",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdbcc",
        "on-tertiary-fixed": "#281800",
        "inverse-on-surface": "#ffede6",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffba45",
        "background": "#fff8f6",
        "surface-dim": "#efd5ca",
        "on-background": "#261812",
        "surface-variant": "#f8ddd2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "xs": "4px",
        "margin-desktop": "64px",
        "lg": "24px",
        "base": "8px",
        "gutter": "16px",
        "margin-mobile": "20px",
        "md": "16px",
        "xl": "32px"
      },
      fontFamily: {
        "label-md": ["Manrope"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-lg": ["Manrope"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Manrope"],
        "body-sm": ["Manrope"],
        "label-lg": ["Manrope"]
      },
      fontSize: {
        "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "20px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
